//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billeder
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Mime { get; set; }
        public byte[] Data { get; set; }
        public int UserId { get; set; }
    }
}
