//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public int id { get; set; }
        public string ownerId { get; set; }
        public string shareId { get; set; }
        public Nullable<int> billedeId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Billeder Billeder { get; set; }
    }
}
